### ISSUE TITLE
Player character stuck being pregnant, Unable to progress in relationship with Benoit

### ISSUE THREAD

**Issue by FOULdragon** [herp-a-derp/Corruption-of-Champions#795] opened 2015-08-22 02:01 UTC
I didn't notice this bug at first but I will start at the beginning of when this bug started showing signs of its presence. I had been trying to raise corruption to get to the bizarre bazaar, I was sexing a lot of imps and other corrupted creatures and I hadn't been getting pregnant. later I went in the swamp a bit and got oviposited 4 times by driders. each oviposition event used my character's vagina. I never showed any signs of pregnancy. even whenever I checked the appearance tab right after being raped by a drider and didn't see any descriptors for being impregnated for eggs. At this point I noticed something was weird. Later I got to the Bazaar and was building reputation with Benoit to get the basilisk womb perk. I used an ovi elixer and even got Benoit's affection up to 100% we have the sex scene and then that's it. I could have sex with him again or even dominate him, but he never says the recipe for the Ovi perk so I can't give him the ingredients I already have.

Here is where the real trouble starts. I have a full belly of eggs and after a while I decide to accelerate the birth time with a couple ovi elixers. I use them and even get to the point where the ovi elixers won't accelerate the pregnancy anymore, but it doesn't trigger going into labor. even going to bed for 8 hours doesn't trigger the birthing event. So now I am permanently stuck in the final stages of pregnancy and Benoit only complains about how much of a bastard his race is.

**Comment by ambjoorn94** [comment] 2015-08-22 09:21
Could you provide your save file?
It would greatly help to see what went wrong if you do.

**Comment by FOULdragon** [comment] 2015-08-22 20:41
I can post the save file whenever I get home from work but could you tell me how? Is there a special process or could I just use the save to file button?

**Comment by FOULdragon** [comment] 2015-08-22 20:42
How to get the save data in a portable format, I mean.

**Comment by ambjoorn94** [comment] 2015-08-22 20:54
All save files are saved in a portable format. It's just that when saving normally, you save in an AppData subfolder. For me, (Windows 8 using latest Firefox, downloaded CoC version) it's located at:
> %appdata%/Macromedia/Flash Player/#SharedObjects/MFPLQ23Q/localhost

However, it would probably be easier for you to find and send if you save to file and upload it at any kind of cloud service, for example google drive or dropbox. (You could even create a repository using Github, but that's a pretty roundabout way to do it)

Of course, you would have to provide a link where one would be able to download it to check for errors.

If possible include a save before the error and after the error.

**Comment by FOULdragon** [comment] 2015-08-23 17:36
alright, I got the two different save files the first one here is the bugged version: https://www.dropbox.com/s/i6ml5j314x7bzjc/CoC_BuggedSave?dl=0

This save is a bit older but as far as I can tell, it doesn't appear bugged. spammed a bunch of ovi elixers and was able to lay eggs once I waited. I was nowhere near getting to the bizarre bazaar and chatting it up with Benoit so I couldn't test that end of it. here is the link to the file though: https://www.dropbox.com/s/fgyoh3zptbi3l1w/CoC_UnbuggedSave?dl=0

**Comment by ambjoorn94** [comment] 2015-08-23 18:11
I tried a little bit with the bugged save.
It doesn't seem bugged for me though.

The data in the file showed that you were pregnant with normal basilisks, how that happened without you having a basilisk womb may be strange. Maybe because you're a bunny-girl?

Anyway, it only had 6 hours left, and the basilisk pregnancy ended properly after 6 hours.

And the matter regarding the basilisk womb perk...
> You rack your brain but can't think of anything that could help Benoit

There is a condition of having an intelligence of 60 or more to be able to unlock talking about the basilisk womb perk.

If the problem with the pregnancy persists, save into a new slot and delete the old save. Some trash data might have accidentally found their way in somehow, it may happen when overwriting saves.

**Comment by FOULdragon** [comment] 2015-08-23 19:56
okay thanks sorry for taking up your time.

**Comment by ambjoorn94** [comment] 2015-08-23 20:10
When you have confirmed that everything works, please close this issue.

**Closed** 2015-08-23 20:41 UTC
